### ISSUE TITLE
References path length

### ISSUE THREAD

**Issue by geo-curious** [NREL/GEOPHIRES-X#134]
Hi all,
I am wondering if it would be possible to shorten the file name lengths for some of the papers in the reference folder. This would help avoid maximum path length problems during pip installation.

**Comment by softwareengineerprogrammer** [comment]
@geo-curious Thanks for bringing this to our attention - it should be possible to shorten them. If you have an example of one that is violating the max path length, what your system's max path length is, that would help me verify the fix should work for you.

**Comment by geo-curious** [comment]
I am on a 260 character limit. I would note the installation works fine when that limit is not violated, but my office machine already operates from a long network path to begin with. Here is an example I think was causing me grief in the references:

References/Tabulated Database of Closed-Loop Geothermal Systems Performance for CloudBased Technical and Economic Modeling of Heat Production and Electricity Generation Beckers et al.pdf

**Comment by geo-curious** [comment]
> pip install https://github.com/softwareengineerprogrammer/GEOPHIRES-X/archive/v3.4.8.zip

This did work on the previous path I tried. Thank you.
