### ISSUE TITLE
MC doesn't work for HIP-RA

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/GEOPHIRES-X#151]
As documented in disabled unit test: https://github.com/NREL/GEOPHIRES-X/blob/d821772a2e13397983343ad7ca710bc2d90a118a/tests/geophires_monte_carlo_tests/test_geophires_monte_carlo.py#L110-L126

And marked by FIXME/TODO: https://github.com/NREL/GEOPHIRES-X/blob/43110be367f7ff3e3ce94d66a61fb32ca19ef1db/src/geophires_monte_carlo/MC_GeoPHIRES3.py#L339-L345

---

Steps to address:

1. Enable `test_hip_ra_monte_carlo` unit test (remove line 110 of `test_geophires_monte_carlo.py`)
2. Fix HIP-RA result parsing implementation - FIXME in line 339 of `MC_GeoPHIRES3.py` indicates probable best place to start
3. Verify fix works by `test_hip_ra_monte_carlo` unit test passing
4. Optional but encouraged - add additional assertions to test to increase coverage
5. Submit PR with fix

**Comment by malcolm-dsider** [comment]
I saw this "FIXME TODO" about HIP-RA, so I switched to trying to run GEOPHIRES with MC_GEOPHIRES. It fails for the same reason.

**Comment by malcolm-dsider** [comment]
The MC tests are passing, but they don’t run from the command line. Something is wrong with the way arguments are being passed or something?!?!? IDK. The unittest framework runs the tests differently than the way things run from the command line. But I can do my coding by running my development test from within the unittest framework, so I can make progress without bothering you tomorrow.

 

I will cancel the meeting, set a bug in the GitHub bug reporting framework, and move on. We can look at it together when you have more time.

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Does the approach in the (very basic) MC user guide work for you? https://softwareengineerprogrammer.github.io/GEOPHIRES-X/Monte-Carlo-User-Guide.html

**Comment by malcolm-dsider** [comment]
That is the approach I am using temporarily to make progress, but we need to fix the command line eventually.

**Comment by softwareengineerprogrammer** [comment]
What command are you using on the command line and what is the resulting
error message?

**Comment by softwareengineerprogrammer** [comment]
<Discussion re: command line issues moved to https://github.com/NREL/GEOPHIRES-X/issues/153>
