### ISSUE TITLE
MC fails to run from command line?

### ISSUE THREAD

**Issue by malcolm-dsider** [NREL/GEOPHIRES-X#153]
MC seems to fail to run from command line? Something to do with the way args are passed?

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider you can try pulling the branch in https://github.com/softwareengineerprogrammer/GEOPHIRES-X/pull/18 (I'll file a PR to merge into main repo later today)

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Added you as reviewer to https://github.com/NREL/GEOPHIRES-X/pull/154 which may address issues you are encountering
