### ISSUE TITLE
Add thermosiphoning example

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/GEOPHIRES-X#188]
Add example with thermosiphoning

**Comment by malcolm-dsider** [comment]
All the closed-loop/AGS examples end up with the thermosiphon effect operating. Are you looking for a non-AGS example?

**Comment by softwareengineerprogrammer** [comment]
> All the closed-loop/AGS examples end up with the thermosiphon effect operating. Are you looking for a non-AGS example?

@malcolm-dsider Correct, looking for a non-AGS example (but thanks for clarification re: AGS)

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Thanks for that explanation, very helpful - and great to know that we in fact already have an EGS thermosiphoning example I wasn't even aware of! I added a comment to `example_SHR-1.txt` referencing this discussion that will be included in whatever PR I make next (https://github.com/softwareengineerprogrammer/GEOPHIRES-X/commit/f043ca5ec9d416a363190bf1153013a8496f946c)
