### ISSUE TITLE
Verify lithostatic vs hydrostatic pressure to determine water properties

### ISSUE THREAD

**Issue by kfbeckers** [NREL/GEOPHIRES-X#195]
Check which pressure is used for calculating water thermo-physical properties

**Comment by softwareengineerprogrammer** [comment]
See relevant previous discussion/work: https://github.com/NREL/GEOPHIRES-X/issues/118?title=Calculate+vapor_pressure_water_kPa+with+pressure+input

**Comment by softwareengineerprogrammer** [comment]
@kfbeckers or @malcolm-dsider can this be considered resolved by https://github.com/NREL/GEOPHIRES-X/pull/217?

**Comment by kfbeckers** [comment]
> @kfbeckers or @malcolm-dsider can this be considered resolved by #217?

I would say yes. We are using hydrostatic pressure now for water properties so this issue is resolved I think.
