### ISSUE TITLE
is FCR being used correctly?

### ISSUE THREAD

**Issue by malcolm-dsider** [NREL/GEOPHIRES-X#206]
A user reports that the fixed charge rate does not seem to function properly for some sensitivity analyses of EGS scenarios.

**Comment by softwareengineerprogrammer** [comment]
Note: we had a question about FCR in the past, for which we wrote an answer that is pending official incorporation into documentation: https://github.com/NREL/GEOPHIRES-X/issues/127. It's possible this FAQ is relevant to the user's report; but we can also investigate this by adding some tests for FCR functionality with or without further input from them.

**Comment by malcolm-dsider** [comment]
The report stated that changing the FCR did not change the LCOE for EGS models.

 

Our benchmark for EGS models with an FCR economic model is example_1. The default value for FCR is 0.05, which produces an LCOE of 9.65 cents/kWh.

If I change the FCR to an unrealistically low number, like 0.0001, I get an LCOE of 3.33 cents/kWh.

If I change the FCR to an unrealistically high number, like 0.8, I get an LCOE of 104.75 cents/kWh.

 

It seems that GEOPHIRES is producing reasonable answers for the edge cases without crashing, so I think we have the correct behavior. We can mark this as “not a bug.” The edge cases seem stable and reasonable, so perhaps we don’t need to add additional testing.
