### ISSUE TITLE
Incomplete outputs in Web UI

### ISSUE THREAD

**Issue by malcolm-dsider** [NREL/GEOPHIRES-X#207]
A user reports that the desktop app produces results in the output that are not being shown in the web UI. For example, the SDAC results are missing both single results and a table. In the case of overpressure calculation, the overpressure table is not reported in the webUI.

**Comment by softwareengineerprogrammer** [comment]
Moved to https://github.com/softwareengineerprogrammer/geothermal-ui/issues/11?title=S-DAC+&+Overpressure+tables+not+rendered since the UI is not part of GEOPHIRES itself

**Comment by softwareengineerprogrammer** [comment]
S-DAC is now rendered per https://github.com/softwareengineerprogrammer/geothermal-ui/issues/11#issuecomment-2725176327 (Overpressure still pending)
