### ISSUE TITLE
Relative imports may be causing some tests to be skipped

### ISSUE THREAD

**Issue by natakokota** [NREL/GEOPHIRES-X#228]
While attempting to resolve issue #22, @aimiktena and I noticed that several tests were raising errors when running all unit tests locally. The specific tests are as follows:

https://github.com/NREL/GEOPHIRES-X/blob/b926e63baac31d5bc8a870641f9f21e6ad0a3932/tests/geophires_x_client_tests/test_geophires_input_parameters.py
https://github.com/NREL/GEOPHIRES-X/blob/b926e63baac31d5bc8a870641f9f21e6ad0a3932/tests/test_parameter.py
https://github.com/NREL/GEOPHIRES-X/blob/b926e63baac31d5bc8a870641f9f21e6ad0a3932/tests/test_base_test_case.py
https://github.com/NREL/GEOPHIRES-X/blob/b926e63baac31d5bc8a870641f9f21e6ad0a3932/tests/geophires_x_tests/test_cylindrical_reservoir.py
https://github.com/NREL/GEOPHIRES-X/blob/b926e63baac31d5bc8a870641f9f21e6ad0a3932/tests/geophires_x_tests/test_reservoir.py
https://github.com/NREL/GEOPHIRES-X/blob/b926e63baac31d5bc8a870641f9f21e6ad0a3932/tests/geophires_x_tests/test_economics.py

**Comment by softwareengineerprogrammer** [comment]
Resolved by https://github.com/NREL/GEOPHIRES-X/pull/230, closing.
