### ISSUE TITLE
Add Geothermal Rising basic economic correlations

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/GEOPHIRES-X#232]
Relevant to https://github.com/NREL/GEOPHIRES-X/issues/169

https://geothermal.org/resources/geothermal-basics

> The Benefits of Geothermal Energy

> Jobs Boost. Geothermal power plants employ about 1.17 persons per MW. Adding related governmental, administrative, and technical jobs, the number increases to 2.13.

> Economy Boost. Over the course of 30 to 50 years an average 20 MW facility will pay nearly $6.3 to $11 million dollars in property taxes plus $12 to $22 million in annual royalties. Seventy-five percent of these royalties ($9.2 to $16.6M) go directly back to the state and county.

> Locally Produced. Geothermal power can offset electricity currently imported into the state, keeping jobs and benefits in state and local communities.

> Near-Zero Carbon Emissions. Geothermal flash plants emit about 5% of the carbon dioxide, 1% of the sulfur dioxide, and less than 1% of the nitrous oxide emitted by a coal-fired plant of equal size, and binary geothermal plants – the most common – produce near-zero emissions.

> Small Footprint. Geothermal has among the smallest surface land footprint per kilowatt (kW) of any power generation technology.

> Reliable. Geothermal power can provide consistent electricity throughout the day and year - continuous baseload power and flexible power to support the needs of variable renewable energy resources, such as wind and solar.

> Sustainable Investment. Energy resource decisions made now for sources of electric power have 40-50 year consequences, or longer. Using renewables like geothermal resources avoids "price spikes" inherent in fossil fuel resource markets. Geothermal energy is an investment in stable, predictable costs. Investing in geothermal power now pays off for decades to come.

**Comment by malcolm-dsider** [comment]
For the record, I think the MW they are talking about here are electricity megawatts (we probably need to confirm that), so the numbers will be different for heat projects. If we can't figure out how to scale the numbers correctly for a heat project, we might have to just report these numbers for projects that contain some electric megawatts.

**Comment by softwareengineerprogrammer** [comment]
Consolidated this with and closing in favor of https://github.com/NREL/GEOPHIRES-X/issues/169
