### ISSUE TITLE
Heating price output as default value instead of input value

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/GEOPHIRES-X#234]
Per @malcolm-dsider

**Comment by malcolm-dsider** [comment]
I did a temporary fix on my local code for this that works.

I simply removed the convenience function when accessing the "value" member of the object, so I went from:
o(econ.CoolingPrice).value[ii]
to
econ.CoolingPrice.value[ii]

and it works correctly.

Another bug related to this - if I use o(econ.CoolingPrice).CurrentUnits.value to print the current units, I get the wrong value - it reports "cents/kWh". if I use econ.CoolingPrice.CurrentUnits.value to get the units, it reports "USD/kWh," which is correct.

So, can we remove the use of the convenience function?

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider do you have an input file that exhibits this issue?

**Comment by malcolm-dsider** [comment]
I did - Project_Owl_HN.txt should do it.

 

The input file says:

 

Starting Heat Sale Price, 0.015

Ending Heat Sale Price, 0.015

 

But the output says:

 


REVENUE & CASHFLOW PROFILE

Heat Price

2

2.5

cents/kWh

**Comment by softwareengineerprogrammer** [comment]
Thanks for clarifying @malcolm-dsider. For reference the full contents of Project_Owl_HN.txt are:

```
************reservoir*************
Reservoir Model, 0
Reservoir Depth, 14087 feet
Gradient 1, 32
Reservoir Volume Option, 4
Reservoir Volume, 3400080000, vol = 3500*1210*914 from map
Reservoir Heat Capacity, 850
Reservoir Density, 2570
Reservoir Thermal Conductivity, 4.2
Reservoir Permeability, 1E-20
Reservoir Porosity, 0.001
Fracture Shape, 3
Fracture Area, 1
Fracture Height, 1
Fracture Width, 1
Number of Fractures, 1
Fracture Separation, 1E4
Cylindrical Reservoir Input Depth, 14087 feet
Cylindrical Reservoir Output Depth, 14087 feet
Cylindrical Reservoir Length, 3.5, max width of campus
Cylindrical Reservoir Radius of Effect, 40


****************Wellbore***********
Is AGS, True
Well Geometry Configuration, 1
Number of Production Wells, 1
Number of Injection Wells, 1
Production Well Diameter, 10
Injection Well Diameter, 10
Production Flow Rate per Well, 50
Reservoir Impedance, 1E-4, there is very little impedance in an AGS system
Total Nonvertical Length, 3500
Number of Multilateral Sections, 6
Multilaterals Cased, False


****************Surface plant************
End-Use Option, 2
Power Plant Type, 6
Ambient Temperature, 20
Surface Temperature, 20

***************Economics****************
Economic Model, 3
Reservoir Stimulation Capital Cost, 0
Exploration Capital Cost, 0

Starting Heat Sale Price, 0.015

Ending Heat Sale Price, 0.015
xHeat Escalation Start Year (5 years, 0, [0-101]) - Number of years after start of project before start of escalation (if ramp model is used)
xHeat Escalation Rate Per Year (0 $/yr, 0, 100) - additional cost per year of price after escalation starts (if ramp model is used)
xProduction Tax Credit Electricity, 0.04, PTC from IRA - can't have both so try one or the other
Investment Tax Credit Rate,0.5, ITC from IRA - can't have both so try one or the other
```

(Issue assigned to myself as I am working on a fix)

**Comment by softwareengineerprogrammer** [comment]
Fix is in https://github.com/NREL/GEOPHIRES-X/pull/231 - the issue was actually that cooling price parameter name was incorrect, see https://github.com/NREL/GEOPHIRES-X/pull/231/commits/ff1f5ea18829b821adc69b105836c43add301333
