### ISSUE TITLE
 Closed loop Configuration, Well Geometry, and Heat Transfer Fluid Configuration options are not enumerated

### ISSUE THREAD

**Issue by malcolm-dsider** [NREL/GEOPHIRES-X#245]
Closed loop Configuration, Well Geometry, and Heat Transfer Fluid Configuration options are not enumerated in the Parameter reference

**Comment by softwareengineerprogrammer** [comment]
I'm actually currently working on enum values so assigned to myself (https://github.com/softwareengineerprogrammer/GEOPHIRES-X/tree/enum-values-in-schema)

**Comment by malcolm-dsider** [comment]
Thanks. I did that as an exercise in class because one of the students pointed this out, and it made sense to show them how to file a bug report.

**Comment by softwareengineerprogrammer** [comment]
Addressed by https://github.com/NREL/GEOPHIRES-X/pull/246
