### ISSUE TITLE
Synchronize workshop case studies with examples

### ISSUE THREAD

**Issue by sws-jonathan** [NREL/GEOPHIRES-X#271]
1. [ ] Project Red: https://gtp.scientificwebservices.com/geophires/?shared-geophires-result-id=479c90cb-4b7d-4e8a-ace6-e5cc578be69c
2. [ ] Cape Station: https://gtp.scientificwebservices.com/geophires/?shared-geophires-result-id=2bfa1f9f-d50b-476e-a05f-90e7f6a84ac1

**Comment by softwareengineerprogrammer** [comment]
Closing in favor of https://github.com/NREL/GEOPHIRES-X/issues/273?title=Synchronize+workshop+case+studies+with+examples (Accidentally created this version with a GitHub profile I use for other purposes)
