### ISSUE TITLE
Fix unit conversion for casing ID when printing output results

### ISSUE THREAD

**Issue by kfbeckers** [NREL/GEOPHIRES-X#51]
Wellbore diameter is incorrectly printed in the output file. For example, unit test example1.txt assumes a diameter of 7" (0.1778 m) but the output results shows 0.005 m:

![image](https://github.com/NREL/python-geophires-x/assets/38221976/a4db9e3b-dedc-4e4d-9448-7acb491256bf)

![image](https://github.com/NREL/python-geophires-x/assets/38221976/8804c4d3-8419-4613-98ef-63aa34a5bb63)

**Comment by softwareengineerprogrammer** [comment]
This was duplicated by https://github.com/NREL/GEOPHIRES-X/issues/92, resolving this issue in favor of it
