### ISSUE TITLE
HIP assumes that ALL the fluid in the reservoir is producible

### ISSUE THREAD

**Issue by malcolm-dsider** [NREL/GEOPHIRES-X#83]
There is a bug in HIP - it assumes that ALL the fluid in the reservoir is producible - this is unrealistic - the producible fluid should be a smaller percentage (probably a user-defined value with a reasonable default, like 20%).

**Comment by softwareengineerprogrammer** [comment]
Relevant work begun in https://github.com/softwareengineerprogrammer/GEOPHIRES-X/pull/3

**Comment by malcolm-dsider** [comment]
I think this is now stale, with all the work done in HIP-RA-X
