### ISSUE TITLE
Add examples/case-studies of real-world geothermal systems

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/GEOPHIRES-X#87]
GEOPHIRES should include input/output examples for real-world geothermal systems. These examples will serve to calibrate and validate GEOPHIRES's calculations.

**Comment by softwareengineerprogrammer** [comment]
Candidate example: [Eavor publishes 4-year update on Eavor-Lite demonstration project in Canada](https://www.thinkgeoenergy.com/eavor-publishes-4-year-update-on-eavor-lite-demonstration-project-in-canada/)

**Comment by softwareengineerprogrammer** [comment]
[Drilling operations at Fervo’s Cape Station show 70% year-over-year reduction in drilling times and pave the way for rapid geothermal deployment](https://fervoenergy.com/fervo-energy-drilling-results-show-rapid-advancement-of-geothermal-performance/)


> Fervo has consistently reduced drilling times and costs in horizontal, high-temperature, deep granite drilling. Though Cape wells are hotter and over 2,100 feet deeper than Project Red wells, Fervo drilled its fastest Cape well in just 21 days, a 70% reduction in drilling time from Fervo’s first horizontal well drilled at Project Red in 2022. This increase in drilling efficiency has translated into significant cost reductions, with drilling costs across the first four horizontal wells at Cape falling from $9.4 million to $4.8 million per well.

Paper: https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2024/Elsadi.pdf?t=1706897516

---

Paper: [Geology, State of Stress, and Heat in Place for a Horizontal Well Geothermal Development
Project at Blue Mountain, Nevada](https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2023/Fercho.pdf)

**Comment by softwareengineerprogrammer** [comment]
SHR: Newberry Volcano in OR = classic example, Maxama recently awarded large grant for additional work

**Comment by softwareengineerprogrammer** [comment]
Fervo https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2023/Fercho.pdf

**Comment by softwareengineerprogrammer** [comment]
CATF report: A Preliminary Techno-Economic Model of Superhot Rock Energy: https://cdn.catf.us/wp-content/uploads/2022/12/16185500/shr-technoeconomic_2023report.pdf

**Comment by softwareengineerprogrammer** [comment]
Initial implementation for Fervo tentatively slated to be on https://github.com/malcolm-dsider/geophires-x-nrel/tree/fervo-case-study

**Comment by softwareengineerprogrammer** [comment]
Fervo: https://eartharxiv.org/repository/view/5704/

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Suggest we don't include the paper PDFs themselves as the large file size has negative performance impacts and other thorny technical complications.

Let's either just use standard citations in context (as I've already done for this paper here: https://github.com/softwareengineerprogrammer/GEOPHIRES-X/commit/030212a90dad26e8b263b0a4638ae35232e0438a#diff-68569bbc99a61381b74ad07a4d3f66b28463215381a74f76739bc8d4206e6402R2-R4), or if necessary, create a separate GEOPHIRES references repository.

**Comment by malcolm-dsider** [comment]
But we already have 13 PDF files in the reference section… and one XLS. And one TXT….

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Yes, those are present and they have/do cause issues so we shouldn't add more; also if we were to create a separate repository as I suggested, we would move those files there.

**Comment by softwareengineerprogrammer** [comment]
https://github.com/NREL/GEOPHIRES-X/issues/288

**Comment by softwareengineerprogrammer** [comment]
https://github.com/NREL/GEOPHIRES-X/issues/290

**Comment by softwareengineerprogrammer** [comment]
Considering this resolved by addition of Fervo Project Red (https://github.com/NREL/GEOPHIRES-X/issues/202?title=Fervo+case+study) and Project Cape (https://github.com/NREL/GEOPHIRES-X/issues/288) examples
