### ISSUE TITLE
Include Plant Type in output

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/GEOPHIRES-X#93]
Include plant type in addition to end-use option, more relevant after some end-use options broken out plant types in https://github.com/softwareengineerprogrammer/GEOPHIRES-X/pull/3/

**Comment by softwareengineerprogrammer** [comment]
Power plant type is already included in output: https://github.com/NREL/GEOPHIRES-X/blob/c2882523c0a664150349a84437f2002ff804556d/src/geophires_x/Outputs.py#L197

Example in test case report: https://github.com/NREL/GEOPHIRES-X/blob/c2882523c0a664150349a84437f2002ff804556d/tests/examples/example1.out#L51

This issue was filed during verbal discussion in which we were under the impression plant type was not in output, but it appears we were mistaken, so there's no issue to fix; resolving.

**Comment by softwareengineerprogrammer** [comment]
Apparently doesn't show up for AC https://jonathanpezzino.com/geothermal/geophires#Z2VvcGhpcmVzX2lucHV0X3BhcmFtZXRlcnM9JTdCJTIyUmVzZXJ2b2lyK01vZGVsJTIyJTNBJTIyMyUyMiUyQyUyMkRyYXdkb3duK1BhcmFtZXRlciUyMiUzQSUyMi4wMDAwMiUyMiUyQyUyMlJlc2Vydm9pcitEZXB0aCUyMiUzQSUyMjIuMSUyMiUyQyUyMk51bWJlcitvZitTZWdtZW50cyUyMiUzQSUyMjElMjIlMkMlMjJHcmFkaWVudCsxJTIyJTNBJTIyNDUlMjIlMkMlMjJNYXhpbXVtK1RlbXBlcmF0dXJlJTIyJTNBJTIyNDAwJTIyJTJDJTIyTnVtYmVyK29mK1Byb2R1Y3Rpb24rV2VsbHMlMjIlM0ElMjIyJTIyJTJDJTIyTnVtYmVyK29mK0luamVjdGlvbitXZWxscyUyMiUzQSUyMjIlMjIlMkMlMjJQcm9kdWN0aW9uK1dlbGwrRGlhbWV0ZXIlMjIlM0ElMjI4LjUlMjIlMkMlMjJJbmplY3Rpb24rV2VsbCtEaWFtZXRlciUyMiUzQSUyMjguNSUyMiUyQyUyMlJhbWV5K1Byb2R1Y3Rpb24rV2VsbGJvcmUrTW9kZWwlMjIlM0ElMjIwJTIyJTJDJTIyUHJvZHVjdGlvbitXZWxsYm9yZStUZW1wZXJhdHVyZStEcm9wJTIyJTNBJTIyNSUyMiUyQyUyMkluamVjdGlvbitXZWxsYm9yZStUZW1wZXJhdHVyZStHYWluJTIyJTNBJTIyMyUyMiUyQyUyMlByb2R1Y3Rpb24rRmxvdytSYXRlK3BlcitXZWxsJTIyJTNBJTIyNTAlMjIlMkMlMjJSZXNlcnZvaXIrVm9sdW1lK09wdGlvbiUyMiUzQSUyMjElMjIlMkMlMjJGcmFjdHVyZStTaGFwZSUyMiUzQSUyMjElMjIlMkMlMjJGcmFjdHVyZStBcmVhJTIyJTNBJTIyMjAwMDAwJTIyJTJDJTIyTnVtYmVyK29mK0ZyYWN0dXJlcyUyMiUzQSUyMjEyJTIyJTJDJTIyRnJhY3R1cmUrU2VwYXJhdGlvbiUyMiUzQSUyMjgwJTIyJTJDJTIySW5qZWN0aXZpdHkrSW5kZXglMjIlM0ElMjI1JTIyJTJDJTIySW5qZWN0aW9uK1RlbXBlcmF0dXJlJTIyJTNBJTIyODAlMjIlMkMlMjJNYXhpbXVtK0RyYXdkb3duJTIyJTNBJTIyMSUyMiUyQyUyMlJlc2Vydm9pcitIZWF0K0NhcGFjaXR5JTIyJTNBJTIyMTAwMCUyMiUyQyUyMlJlc2Vydm9pcitEZW5zaXR5JTIyJTNBJTIyMzAwMCUyMiUyQyUyMlJlc2Vydm9pcitUaGVybWFsK0NvbmR1Y3Rpdml0eSUyMiUzQSUyMjMlMjIlMkMlMjJXYXRlcitMb3NzK0ZyYWN0aW9uJTIyJTNBJTIyMC4wMiUyMiUyQyUyMkVuZC1Vc2UrT3B0aW9uJTIyJTNBJTIyMiUyMiUyQyUyMlBvd2VyK1BsYW50K1R5cGUlMjIlM0ElMjI1JTIyJTJDJTIyQ2lyY3VsYXRpb24rUHVtcCtFZmZpY2llbmN5JTIyJTNBJTIyLjgwJTIyJTJDJTIyVXRpbGl6YXRpb24rRmFjdG9yJTIyJTNBJTIyLjklMjIlMkMlMjJFbmQtVXNlK0VmZmljaWVuY3krRmFjdG9yJTIyJTNBJTIyLjklMjIlMkMlMjJTdXJmYWNlK1RlbXBlcmF0dXJlJTIyJTNBJTIyMTUlMjIlMkMlMjJBbWJpZW50K1RlbXBlcmF0dXJlJTIyJTNBJTIyMTUlMjIlMkMlMjJBYnNvcnB0aW9uK0NoaWxsZXIrQ09QJTIyJTNBJTIyMC43MiUyMiUyQyUyMlBsYW50K0xpZmV0aW1lJTIyJTNBJTIyMzAlMjIlMkMlMjJFY29ub21pYytNb2RlbCUyMiUzQSUyMjIlMjIlMkMlMjJEaXNjb3VudCtSYXRlJTIyJTNBJTIyMC4wNSUyMiUyQyUyMkluZmxhdGlvbitSYXRlK0R1cmluZytDb25zdHJ1Y3Rpb24lMjIlM0ElMjIwLjA1JTIyJTJDJTIyV2VsbCtEcmlsbGluZythbmQrQ29tcGxldGlvbitDYXBpdGFsK0Nvc3QrQWRqdXN0bWVudCtGYWN0b3IlMjIlM0ElMjIxJTIyJTJDJTIyV2VsbCtEcmlsbGluZytDb3N0K0NvcnJlbGF0aW9uJTIyJTNBJTIyMSUyMiUyQyUyMlJlc2Vydm9pcitTdGltdWxhdGlvbitDYXBpdGFsK0Nvc3QrQWRqdXN0bWVudCtGYWN0b3IlMjIlM0ElMjIxJTIyJTJDJTIyU3VyZmFjZStQbGFudCtDYXBpdGFsK0Nvc3QrQWRqdXN0bWVudCtGYWN0b3IlMjIlM0ElMjIxJTIyJTJDJTIyRmllbGQrR2F0aGVyaW5nK1N5c3RlbStDYXBpdGFsK0Nvc3QrQWRqdXN0bWVudCtGYWN0b3IlMjIlM0ElMjIxJTIyJTJDJTIyRXhwbG9yYXRpb24rQ2FwaXRhbCtDb3N0K0FkanVzdG1lbnQrRmFjdG9yJTIyJTNBJTIyMSUyMiUyQyUyMldlbGxmaWVsZCtPJTI2TStDb3N0K0FkanVzdG1lbnQrRmFjdG9yJTIyJTNBJTIyMSUyMiUyQyUyMlN1cmZhY2UrUGxhbnQrTyUyNk0rQ29zdCtBZGp1c3RtZW50K0ZhY3RvciUyMiUzQSUyMjElMjIlMkMlMjJXYXRlcitDb3N0K0FkanVzdG1lbnQrRmFjdG9yJTIyJTNBJTIyMSUyMiUyQyUyMkVsZWN0cmljaXR5K1JhdGUlMjIlM0ElMjIuMDclMjIlMkMlMjJBYnNvcnB0aW9uK0NoaWxsZXIrQ2FwaXRhbCtDb3N0JTIyJTNBJTIyMy43NCUyMiUyQyUyMkFic29ycHRpb24rQ2hpbGxlcitPJTI2TStDb3N0JTIyJTNBJTIyMC4wNjUlMjIlMkMlMjJQcmludCtPdXRwdXQrdG8rQ29uc29sZSUyMiUzQSUyMjElMjIlMkMlMjJUaW1lK3N0ZXBzK3Blcit5ZWFyJTIyJTNBJTIyMTAlMjIlMkMlMjJTdGFydGluZytDb29saW5nK1NhbGUrUHJpY2UlMjIlM0ElMjIwLjA2NTUlMjIlMkMlMjJFbmRpbmcrQ29vbGluZytTYWxlK1ByaWNlJTIyJTNBJTIyMC4wNjU1JTIyJTdE

**Comment by softwareengineerprogrammer** [comment]
Include enum value instead of just ID (i.e. ABSORPTION_CHILLER instead of 9)

**Comment by kfbeckers** [comment]
addressed with https://github.com/NREL/GEOPHIRES-X/pull/183
